<?php
require_once __DIR__.'/../includes/config.php'; require_admin(); $edit=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf(); $action=(string)($_POST['action']??'');
 if($action==='save'){ $id=(int)($_POST['id']??0); $name=trim((string)($_POST['name']??'')); $description=trim((string)($_POST['description']??'')); if($name===''){flash('error','Nama kategori wajib diisi.');} else { try{ if($id>0){$s=db()->prepare('UPDATE categories SET name=?,description=? WHERE id=?');$s->bind_param('ssi',$name,$description,$id);}else{$s=db()->prepare('INSERT INTO categories(name,description) VALUES(?,?)');$s->bind_param('ss',$name,$description);} $s->execute();$s->close();flash('success','Kategori berhasil disimpan.');}catch(Throwable $e){flash('error','Kategori gagal disimpan. Nama mungkin sudah digunakan.');}} }
 elseif($action==='delete'){ $id=(int)($_POST['id']??0); $s=db()->prepare('DELETE FROM categories WHERE id=?');$s->bind_param('i',$id);$s->execute();$s->close();flash('success','Kategori berhasil dihapus.'); }
 redirect('admin/categories.php');
}
if(isset($_GET['edit'])){$id=(int)$_GET['edit'];$s=db()->prepare('SELECT * FROM categories WHERE id=?');$s->bind_param('i',$id);$s->execute();$edit=$s->get_result()->fetch_assoc();$s->close();}
$categories=db()->query('SELECT c.*,COUNT(p.id) AS product_count FROM categories c LEFT JOIN products p ON p.category_id=c.id GROUP BY c.id ORDER BY c.name'); $pageTitle='Kategori'; require __DIR__.'/admin_header.php';
?>
<div class="section-head"><div><span class="eyebrow">CRUD</span><h1>Manajemen Kategori</h1></div></div><div class="admin-two-col"><div class="panel"><h3><?= $edit?'Edit':'Tambah' ?> Kategori</h3><form method="post" class="form-stack"><?= csrf_field() ?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><label>Nama<input name="name" value="<?= e($edit['name']??'') ?>" required></label><label>Deskripsi<textarea name="description" rows="4"><?= e($edit['description']??'') ?></textarea></label><button class="btn btn-primary" type="submit">Simpan</button><?php if($edit): ?><a class="btn btn-outline" href="<?= e(url('admin/categories.php')) ?>">Batal</a><?php endif; ?></form></div><div class="panel"><h3>Daftar Kategori</h3><div class="table-wrap"><table class="table"><thead><tr><th>Nama</th><th>Produk</th><th>Aksi</th></tr></thead><tbody><?php while($cat=$categories->fetch_assoc()): ?><tr><td><strong><?= e($cat['name']) ?></strong><small><?= e($cat['description']) ?></small></td><td><?= (int)$cat['product_count'] ?></td><td class="actions"><a class="btn btn-outline btn-sm" href="<?= e(url('admin/categories.php?edit='.$cat['id'])) ?>">Edit</a><form method="post" onsubmit="return confirm('Hapus kategori ini? Produk terkait akan menjadi tanpa kategori.')"><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$cat['id'] ?>"><button class="btn btn-danger btn-sm">Hapus</button></form></td></tr><?php endwhile; ?></tbody></table></div></div></div>
<?php require __DIR__.'/admin_footer.php'; ?>
