<?php
require_once __DIR__.'/../includes/config.php'; require_admin();
function make_slug(string $text): string{if(function_exists('iconv')){$text=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$text)?:$text;}$text=strtolower(preg_replace('/[^a-zA-Z0-9]+/','-',$text)??'');return trim($text,'-')?:'produk-'.time();}
function handle_upload(?string $current=null): ?string { if(empty($_FILES['image']['name']))return $current; if($_FILES['image']['error']!==UPLOAD_ERR_OK)throw new RuntimeException('Upload gambar gagal.'); if($_FILES['image']['size']>2*1024*1024)throw new RuntimeException('Ukuran gambar maksimal 2 MB.'); $ext=strtolower(pathinfo($_FILES['image']['name'],PATHINFO_EXTENSION)); if(!in_array($ext,['jpg','jpeg','png','webp'],true))throw new RuntimeException('Format gambar harus JPG, PNG, atau WEBP.'); $name='product-'.bin2hex(random_bytes(6)).'.'.$ext; $target=__DIR__.'/../public/uploads/'.$name; if(!move_uploaded_file($_FILES['image']['tmp_name'],$target))throw new RuntimeException('Gagal menyimpan file gambar.'); if($current && str_starts_with($current,'public/uploads/') && is_file(__DIR__.'/../'.$current))@unlink(__DIR__.'/../'.$current); return 'public/uploads/'.$name; }
$edit=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=(string)($_POST['action']??'');
 if($action==='save'){$id=(int)($_POST['id']??0);$categoryId=(int)($_POST['category_id']??0);$name=trim((string)($_POST['name']??''));$description=trim((string)($_POST['description']??''));$price=(float)($_POST['price']??0);$stock=max(0,(int)($_POST['stock']??0));$sizes=trim((string)($_POST['sizes']??''));$active=isset($_POST['is_active'])?1:0;$current=trim((string)($_POST['current_image']??'')); if($name===''||$price<0||$sizes===''){flash('error','Nama, harga, dan ukuran wajib diisi.');redirect('admin/products.php'.($id?'?edit='.$id:''));} try{$image=handle_upload($current?:null);$slug=make_slug($name);$check=db()->prepare('SELECT id FROM products WHERE slug=? AND id<>?');$check->bind_param('si',$slug,$id);$check->execute();if($check->get_result()->num_rows>0)$slug.='-'.time();$check->close();$categoryValue=$categoryId>0?$categoryId:null;if($id>0){$s=db()->prepare('UPDATE products SET category_id=?,name=?,slug=?,description=?,price=?,stock=?,sizes=?,image_path=?,is_active=? WHERE id=?');$s->bind_param('isssdissii',$categoryValue,$name,$slug,$description,$price,$stock,$sizes,$image,$active,$id);}else{$s=db()->prepare('INSERT INTO products(category_id,name,slug,description,price,stock,sizes,image_path,is_active) VALUES(?,?,?,?,?,?,?,?,?)');$s->bind_param('isssdissi',$categoryValue,$name,$slug,$description,$price,$stock,$sizes,$image,$active);} $s->execute();$s->close();flash('success','Produk berhasil disimpan.');}catch(Throwable $e){flash('error',$e->getMessage());}}
 elseif($action==='delete'){$id=(int)($_POST['id']??0);$get=db()->prepare('SELECT image_path FROM products WHERE id=?');$get->bind_param('i',$id);$get->execute();$image=$get->get_result()->fetch_assoc()['image_path']??null;$get->close();$s=db()->prepare('DELETE FROM products WHERE id=?');$s->bind_param('i',$id);$s->execute();$s->close();if($image&&str_starts_with($image,'public/uploads/')&&is_file(__DIR__.'/../'.$image))@unlink(__DIR__.'/../'.$image);flash('success','Produk berhasil dihapus.');}
 redirect('admin/products.php');
}
if(isset($_GET['edit'])){$id=(int)$_GET['edit'];$s=db()->prepare('SELECT * FROM products WHERE id=?');$s->bind_param('i',$id);$s->execute();$edit=$s->get_result()->fetch_assoc();$s->close();}
$categories=db()->query('SELECT id,name FROM categories ORDER BY name');$products=db()->query('SELECT p.*,c.name AS category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id ORDER BY p.created_at DESC');$pageTitle='Produk';require __DIR__.'/admin_header.php';
?>
<div class="section-head"><div><span class="eyebrow">CRUD</span><h1>Manajemen Produk</h1></div></div><div class="admin-two-col product-admin-grid"><div class="panel"><h3><?= $edit?'Edit':'Tambah' ?> Produk</h3><form method="post" enctype="multipart/form-data" class="form-stack"><?= csrf_field() ?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><input type="hidden" name="current_image" value="<?= e($edit['image_path']??'') ?>"><label>Kategori<select name="category_id"><option value="0">Tanpa kategori</option><?php while($cat=$categories->fetch_assoc()): ?><option value="<?= (int)$cat['id'] ?>" <?= (int)($edit['category_id']??0)===(int)$cat['id']?'selected':'' ?>><?= e($cat['name']) ?></option><?php endwhile; ?></select></label><label>Nama produk<input name="name" value="<?= e($edit['name']??'') ?>" required></label><label>Deskripsi<textarea name="description" rows="4"><?= e($edit['description']??'') ?></textarea></label><div class="form-row"><label>Harga<input type="number" name="price" min="0" step="1000" value="<?= e($edit['price']??'0') ?>" required></label><label>Stok<input type="number" name="stock" min="0" value="<?= e($edit['stock']??'0') ?>" required></label></div><label>Ukuran<input name="sizes" value="<?= e($edit['sizes']??'38,39,40,41,42') ?>" placeholder="38,39,40,41,42" required></label><label>Gambar (maksimal 2 MB)<input type="file" name="image" accept=".jpg,.jpeg,.png,.webp"></label><label class="check-label"><input type="checkbox" name="is_active" <?= !isset($edit['is_active'])||(int)$edit['is_active']===1?'checked':'' ?>> Produk aktif</label><button class="btn btn-primary" type="submit">Simpan Produk</button><?php if($edit): ?><a class="btn btn-outline" href="<?= e(url('admin/products.php')) ?>">Batal</a><?php endif; ?></form></div><div class="panel"><h3>Daftar Produk</h3><div class="table-wrap"><table class="table"><thead><tr><th>Produk</th><th>Harga</th><th>Stok</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php while($p=$products->fetch_assoc()): ?><tr><td><strong><?= e($p['name']) ?></strong><small><?= e($p['category_name']??'Tanpa kategori') ?></small></td><td><?= rupiah($p['price']) ?></td><td><?= (int)$p['stock'] ?></td><td><?= (int)$p['is_active']?'Aktif':'Nonaktif' ?></td><td class="actions"><a class="btn btn-outline btn-sm" href="<?= e(url('admin/products.php?edit='.$p['id'])) ?>">Edit</a><form method="post" onsubmit="return confirm('Hapus produk ini?')"><?= csrf_field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$p['id'] ?>"><button class="btn btn-danger btn-sm">Hapus</button></form></td></tr><?php endwhile; ?></tbody></table></div></div></div>
<?php require __DIR__.'/admin_footer.php'; ?>
